### ISSUE TITLE
tile-join does not remove attribute

### ISSUE THREAD

**Issue by x9xjdzz9** [mapbox/tippecanoe#334] opened 2016-12-13 17:01 UTC
Using the following command does not remove the "name" attribute from my mbtile.

tile-join -x name -o new-filename old-filename

**Comment by ericfischer** [comment] 2016-12-13 18:56
Can you provide a more detailed example of what is failing? If I do

```
$ ./tippecanoe -f -o foo.mbtiles tests/ne_110m_populated_places/in.json
$ ./tippecanoe-decode foo.mbtiles | grep FEATURECLA | head -2
$ ./tile-join -f -x FEATURECLA -o bar.mbtiles foo.mbtiles
$ ./tippecanoe-decode bar.mbtiles | grep FEATURECLA
```

the `FEATURECLA` attribute is removed from the second-stage `bar.mbtiles` as intended. I'd like to understand what is happening differently for you.

**Comment by x9xjdzz9** [comment] 2016-12-13 19:28
Using tippecanoe-decode, I noticed that there was a \u000d character after the attribute name. The csv file from which the attribute originated was generated in Windows. Once I converted the line endings in the csv file to UNIX format and re-imported the attributes, the extra character was no longer there and I was able to remove the attribute successfully.

**Comment by ericfischer** [comment] 2016-12-13 19:33
Thanks. I should filter out \r since other people will probably have files from Windows with the same problem, and there's no reason to treat it as significant.

**Comment by ericfischer** [comment] 2016-12-13 22:36
This will be fixed in https://github.com/mapbox/tippecanoe/pull/336

**Closed** 2016-12-13 23:24 UTC
