### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by yurukov** [mapbox/tippecanoe#71] opened 2015-07-26 18:41 UTC
I'm trying to read a few thousand files. All good until it reaches 53%. Then I get a segmentation fault. Couldn't find the core. The data is 1.6G of multipolygons in 3 mil features.

    Sorting 3023823 features
    Sorting part 2 of 2
    3023823 features, 206291031 bytes of geometry, 39974100 bytes of metadata, 50136989 bytes of string pool
    Segmentation fault (core dumped)

**Comment by ericfischer** [comment] 2015-07-26 18:48
Thanks. Any chance you could run this under gdb or lldb and give me a stack trace of the crash, or a copy of the input file so I can see if I can make it crash myself? What OS are you using?

**Comment by ericfischer** [comment] 2015-07-26 18:49
Are you giving all the thousands of files as separate command line arguments, or concatenating them together?

**Comment by yurukov** [comment] 2015-07-26 22:05
Ubuntu 64b. I tried all together and as one file. In both cases it cuts off at 53.3%. Here's the data: http://cadastre.obshtestvo.bg/parcels.zip It's 350Mb zipped (1.6Gb) of multiplygons with property areas in Bulgaria. I did a "-y purp" to combine them in up to 10 groups. The loading runs OK. Tried it on a two different machines. On the road now. Will try to run with a stack trace tomorrow.

**Comment by yurukov** [comment] 2015-07-27 00:23
Cross that. I just sshed from my phone. I redid the common file with mapshaper and it worked. Separate files still fail though. Here's the trace.

    #0  pool (p=0x7fed0000000b, s=0x7fedecb64007 "3", type=2) at pool.c:18
    #1  0x0000000000411541 in retrieve_string (stringpool=0x7fedecb64000 "\001purp", p=0x7fed0000000b, 
        f=0x7ffe5271b550) at tile.cc:199
    #2  decode_meta (only=0x0, intmeta=0x7ffe5271b610, file_keys=0x26e5e40, values=0x7fed0000000b, 
        keys=0x7ffe5270f1c8, stringpool=0x7fedecb64000 "\001purp", meta=0x7ffe5271b550) at tile.cc:216
    #3  write_tile (geoms=geoms@entry=0x7ffe5271bae0, metabase=metabase@entry=0x7fedea9de000 "\002", 
        stringpool=stringpool@entry=0x7fedecb64000 "\001purp", file_bbox=file_bbox@entry=0x7ffe5272d8d0, 
        z=8, tx=144, ty=92, detail=10, min_detail=min_detail@entry=7, basezoom=basezoom@entry=14, 
        file_keys=file_keys@entry=0x7ffe5271edb0, layernames=layernames@entry=0x7ffe5271bf20, 
        outdb=outdb@entry=0x1ff0328, droprate=droprate@entry=2,5, buffer=buffer@entry=5, 
        fname=fname@entry=0x7ffe5273190a "out.mbtiles", geomfile=geomfile@entry=0x7ffe5271bc70, 
        file_minzoom=file_minzoom@entry=8, file_maxzoom=file_maxzoom@entry=14, todo=todo@entry=222459040, 
        geomstart=geomstart@entry=0x7fedecba2000 "\020\220", along=along@entry=0, gamma=gamma@entry=0, 
        nlayers=nlayers@entry=1488, prevent=prevent@entry=0x7ffe5272ddf0 "") at tile.cc:676
    #4  0x0000000000413841 in traverse_zooms (geomfd=geomfd@entry=0x7ffe5272da00, 
        geom_size=geom_size@entry=0x7ffe5272db00, metabase=metabase@entry=0x7fedea9de000 "\002", 
        stringpool=stringpool@entry=0x7fedecb64000 "\001purp", file_bbox=file_bbox@entry=0x7ffe5272d8d0, 
        file_keys=file_keys@entry=0x7ffe5271edb0, midx=midx@entry=0x7ffe5272d840, 
        midy=midy@entry=0x7ffe5272d850, layernames=0x7ffe5271bf20, maxzoom=maxzoom@entry=14, minzoom=8, 
        outdb=0x1ff0328, droprate=droprate@entry=2,5, buffer=5, fname=0x7ffe5273190a "out.mbtiles", 
        tmpdir=0x421d24 "/tmp", gamma=gamma@entry=0, nlayers=1488, prevent=0x7ffe5272ddf0 "", 
        full_detail=12, low_detail=10, min_detail=7) at tile.cc:852
    #5  0x0000000000406110 in read_json (argc=<optimized out>, argv=<optimized out>, 
        fname=<optimized out>, layername=<optimized out>, layername@entry=0x0, maxzoom=maxzoom@entry=14, 
        minzoom=minzoom@entry=8, outdb=outdb@entry=0x1ff0328, exclude=exclude@entry=0x7ffe5272ddb0, 
        include=include@entry=0x7ffe5272ddd0, exclude_all=exclude_all@entry=1, 
        droprate=droprate@entry=2,5, buffer=buffer@entry=5, tmpdir=tmpdir@entry=0x421d24 "/tmp", 
        gamma=gamma@entry=0, prevent=prevent@entry=0x7ffe5272ddf0 "") at geojson.c:993
    #6  0x0000000000404095 in main (argc=1495, argv=0x7ffe5272e018) at geojson.c:1190

**Comment by ericfischer** [comment] 2015-07-27 22:45
Thanks. I've downloaded the files and it's reproducible for me too.

    3023823 features, 206336668 bytes of geometry, 87815156 bytes of metadata, 50177693 bytes of string pool
      5.0%  0/0/0
    Program received signal SIGSEGV, Segmentation fault.
    pool (p=0x7ffff6b369f8, s=0x7ffff3fa626a "10135.2505.45", type=1) at pool.c:20
    20		while (*v != NULL) {

**Comment by ericfischer** [comment] 2015-07-27 22:55
This is kind of an interesting test case, because I've never tried to make tiles with anywhere close to as many layers as 1487 before, and probably most other people haven't either. It's really stretching the limit of the tile format.

**Comment by ericfischer** [comment] 2015-07-27 23:06
Oh, that is it. I assumed that there would never be more than 128 layers and kept the number in a signed byte. I'll use the standard int encoding now that there are variable-length ints everywhere anyway.

**Comment by ericfischer** [comment] 2015-07-27 23:23
Should be fixed in 32179b7. Thanks for finding the bug!

**Closed by ericfischer** 2015-07-27 23:23 UTC

**Comment by yurukov** [comment] 2015-07-28 06:48
Great. Thanks
