### ISSUE TITLE
Error "Vector tile Layer has an unsupported version" when uploading file to Mapbox 

### ISSUE THREAD

**Issue by jmcazaux** [mapbox/tippecanoe#261] opened 2016-06-16 14:31 UTC
Hi there,
I am building vector MBtiles file with tippecanoe, but when uploading to Mapbox, I jave the following error message `Vector tile Layer has an unsupported version`

Neither tile-enumerate nor tile-decode complain when opening this file.
I do not have any error message while building it.

Any idea where this could come from ?

Many thanks,
JM

**Comment by ericfischer** [comment] 2016-06-16 17:06
I haven't seen that problem. What version of tippecanoe are you using? (From `tippecanoe --version`)

**Comment by jmcazaux** [comment] 2016-06-16 17:13
Hi Eric,
it is 1.11.9.

**Comment by jmcazaux** [comment] 2016-06-16 17:23
I have just investigated more.

The tileset is a joint of individual levels.

The individual levels all load on their own, but they do not load when joint.

**Comment by jmcazaux** [comment] 2016-06-16 17:32
Same after upgrading to 1.12.0.

**Comment by ericfischer** [comment] 2016-06-16 17:43
Thanks. So this must be a tile-join bug, not in tippecanoe proper. I'll try to reproduce it.

**Comment by jmcazaux** [comment] 2016-06-16 18:19
Does it help if I give you access to my data ?

**Comment by jmcazaux** [comment] 2016-06-16 18:25
Eric, just sent you an email with a link to the data.

**Comment by ericfischer** [comment] 2016-06-16 19:09
Thanks. It looks like this is just an uninitialized variable in mbtiles parsing and I should have a fix checked in later today.

**Comment by ericfischer** [comment] 2016-06-16 19:34
Should be fixed in https://github.com/mapbox/tippecanoe/pull/262. I'll merge it once the tests all complete.

**Comment by ericfischer** [comment] 2016-06-16 20:12
Thanks for finding this bug!

**Closed by ericfischer** 2016-06-16 20:12 UTC
