### ISSUE TITLE
Too many open files crash

### ISSUE THREAD

**Issue by timiyay** [mapbox/tippecanoe#211] opened 2016-04-14 00:02 UTC
**versions:** 1.9.11, 1.9.12

I'm taking the latest versions of `tippecanoe` for a spin, rerunning some test sets I created a couple of months ago. These tests were dev experiments, searching for the best way to compile a large contours dataset into MBTiles. As such, I was experimenting with the 'Doing more' flags, such as coalescing and reversal, to see their effects.

In the latest 2 versions of `tippecanoe`, I am now getting a crash:

```
/tmp/index.KVKfnuY8: Too many open files
```

This crash occurs 100% of the time - no test runs complete successfully.

Through process of elimination, I found that it was the combination of the `-P` (multithreading), `-ar` (line direction reversal), and `-Z -z` (zoom) flags that caused the bug

**Steps to Reproduce**

1. use `ogr2ogr` to export a ~100MB contours dataset to GeoJSON
2. (optional) use `jq` to extract the features into line-delimited JSON
    * `jq -c '.features[]' contours.json > contours_line.json`
    * the crash occurs whether this step is performed or not
3. run `tippecanoe` with multithreading and reordering parameters
    * `tippecanoe -Z13 -z16 -P -ar -o contours.mbtiles contours_line.json`
    * my actual command: `tippecanoe -f -P -Z13 -z16 -ac -ar -ao -o contours.mbtiles contours_line.json`

This will crash reliably.

**Workaround**

I found that the bug did _not_ occur if:  

* I did not use the `-P` flag, or
* I did not use the `-ar` flag, or
* I did not constrain the zoom levels with `-Z13 -z16`

I may revisit these test sets, to see if I even need `-ar` anymore. At the time, it was required to avoid segmentation faults, similar to this issue (https://github.com/mapbox/tippecanoe/issues/198).

Let me know if this isn't reproducible by anyone else, and I can host the 100MB GeoJSON somewhere for testing.

**Comment by ericfischer** [comment] 2016-04-14 00:13
Oh no! I must have done the math wrong in https://github.com/mapbox/tippecanoe/pull/202, which uses a lot of simultaneous open files in the "reordering geometry" phase. @timiyay, what OS are you using? Can you tell me the output of `ulimit -a` so I can know how many file descriptors your system makes available? It would also be very useful to have a copy of your file for testing, although I'm surprised the same problem doesn't manifest with other files.

**Comment by ericfischer** [comment] 2016-04-14 00:19
Also could you say how many CPUs your system has? The `-P` effect makes sense, because each additional threads consumes file descriptors for its index, metadata, geometry, and string pool. I don't know why `-ar` should make a difference. `-z16` might have an effect because it means it will skip over some zoom levels, so the zoom level 0 pass will consume more temporary files than if it were just producing zoom level 1.

**Comment by timiyay** [comment] 2016-04-14 00:22
@ericfischer

I haven't tested on all of my files yet, as it has taken me a while to iterate on this single one. I'll update the issue with the results of other files, and see if it's just one files.

I'm on OSX El Capitan 11.4, on an early 2011 Macbook Pro 15". It has an Intel Core i7 2.2Ghz with 4 CPUs.
```
$ ulimit -a 
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       709
-n: file descriptors                4864
```

**Comment by timiyay** [comment] 2016-04-14 00:31
Ran the same commands on the same data on a Macbook Air Mid 2013, with 1.3GhZ Intel Core i5 (2 CPUs).

The bug _did not_ occur - the test run finished just fine.

**Comment by ericfischer** [comment] 2016-04-14 00:34
Thanks. You have more open files available by default than I do, but I haven't been able to reproduce the problem myself yet even by raising the limit.

**Comment by timiyay** [comment] 2016-04-14 00:39
I've tried it on some other extracts from the same data source, with mixed results that loosely correlate on file size.

The originally reported file was for 10m index contours.

`5m`: failed (~280MB geojson)
`10m`: failed (~100MB geosjon)
`20m`: passed (~20MB geojson)

I'll continue collecting info about this, as I iterate on our contours-to-mbtiles process. I'll do some more-comprehensive tests, and also figure out whether it's something else on the specific machine that is messing with the program. I use a lot of JS file watchers like watchman, guard, webpack, gulp, ember-cli, livereload, etc, which sometimes eat up file limits.

It'll take a while, probably a few days. It's slow going, as I shoehorn it between other work, while waiting for the various tools (`ogr2ogr`, `tippecanoe`, etc) to finish.

**Comment by ericfischer** [comment] 2016-04-14 00:41
If it's possible to see a copy of the file, that would probably help a lot in debugging it. Maybe it is hitting a system-wide limit on the number of files even though it is staying under the per-process limit. I can add a check for that, but it's hard to make the code reliable if I can't make the problem happen reliably.

**Comment by ericfischer** [comment] 2016-04-14 00:44
Apparently the total system has a limit on the number of open files:

```
$ sysctl kern.maxfiles
kern.maxfiles: 12288
```

My computer has 7689 open independent of tippecanoe, according to `lsof`, so 4864 more would get close to hitting the wall if you have more open from other processes than I do. I'll try to hit the system limit so I can get tippecanoe to fail that way, and add a check to reduce its file usage if it gets close.

**Comment by ericfischer** [comment] 2016-04-14 01:07
When you get a chance, could you see if https://github.com/mapbox/tippecanoe/pull/212 fixes it for you?

**Comment by timiyay** [comment] 2016-04-14 01:23
@ericfischer #212 fixes the `Too many open files` error.

Looks like you've nailed it.

The test runs complete now, and I'm uploading the output MBTiles to check their output.

**Comment by timiyay** [comment] 2016-04-14 01:35
Output is as expected, all looking good.

Thanks for the quick fix!

**Comment by ericfischer** [comment] 2016-04-14 02:14
Great! I will merge it after I clean it up a little more.

**Comment by timiyay** [comment] 2016-04-14 02:24
I uploaded a zip file to Dropbox, containing the 3 different contour GeoJSON files described above: https://github.com/mapbox/tippecanoe/issues/211#issuecomment-209701819

https://www.dropbox.com/s/h2ek9p9jarcj5jp/contour_geojson.zip?dl=0

The 5m and 10m contour extracts were failing, and the 20m were passing.

You may not need it, but if you were able to figure out a way to repro and build tests, I thought they might be useful.

It could def be machine specific, so let me know if there's any extra traces or tests I could run on my 2011 MBP to document the issue.

**Comment by ericfischer** [comment] 2016-04-14 17:00
Oh! The `-ar` is the real problem! I am a fool and accidentally reused an option letter, and the `-ar` was making it use a deeply recursive radix sort (meant for testing that recursion works at all) for no good reason. I'll add a sanity check to make sure I don't screw that up again.

**Comment by ericfischer** [comment] 2016-04-14 17:34
Thanks for finding this! It should be fixed for real now. https://github.com/mapbox/tippecanoe/releases/tag/1.9.13

**Closed** 2016-04-14 17:39 UTC
