### ISSUE TITLE
running tippecanoe on larger geo json files

### ISSUE THREAD

**Issue by nodefiend** [mapbox/tippecanoe#394] opened 2017-04-12 18:31 UTC
i have 2 layers that need to be proccessed into tippecanoe, one is 57gb (water) and the other is 230gb(roads)

i had planned on running tippecaoe with my options on just 1 zoom layer at a time and using tile-join to join the mbtiles files together but it is killing the process immediately 

is there any suggestions ? or would you know how much processing power would be needed to run this conversion?

<img width="631" alt="screen shot 2017-04-12 at 11 14 58 am" src="https://cloud.githubusercontent.com/assets/10778319/24973428/80558d44-1f73-11e7-86a0-789c0621ce57.png">

**Comment by ericfischer** [comment] 2017-04-12 18:48
The abrupt "Killed" message comes up when the operating system kills the Tippecanoe process because the system is running out of memory.

The `Warning: not finding any GeoJSON features or geometries in input` message is the big warning sign here. It is parsing the JSON into memory, and is apparently not finding any GeoJSON within it. So it is just building a gigantic parse tree of the JSON in memory, and eventually crashing because the parse tree gets huge.

You should take a closer look at `z14_transportation.geojson` and make sure it actually is valid GeoJSON.

**Comment by nodefiend** [comment] 2017-04-12 19:30
i simply used ``tippecanoe-decode`` and removed layers out of a giant Planet.mbtiles file

It looks like the other json files that i have been using at a smaller scale, those maps appeared to render fine:


<img width="858" alt="screen shot 2017-04-12 at 12 10 20 pm" src="https://cloud.githubusercontent.com/assets/10778319/24975752/a4c6e7ba-1f7b-11e7-9018-ea69e4be26d5.png">

Heres the print out (10 lines )of the json file.

```
{ "type": "FeatureCollection", "properties": {
"attribution": "<a href=\"http://openmaptiles.org/\" target=\"_blank\">&copy; OpenMapTiles</a> <a href=\"http://www.openstreetmap.org/about/\" target=\"_blank\">&copy; OpenStreetMap contributors</a>",
"bounds": "-180,-85.0511,180,85.0511",
"center": "-12.2168,28.6135,4",
"description": "http://openmaptiles.org",
"format": "pbf",
"id": "openmaptiles",
"json": "{ \"vector_layers\": [ { \"id\": \"water\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\" } }, { \"id\": \"waterway\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"name\": \"String\", \"class\": \"String\" } }, { \"id\": \"landcover\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\", \"subclass\": \"String\" } }, { \"id\": \"landuse\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\" } }, { \"id\": \"park\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\" } }, { \"id\": \"boundary\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"admin_level\": \"Number\" } }, { \"id\": \"aeroway\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\" } }, { \"id\": \"transportation\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\", \"oneway\": \"Number\", \"ramp\": \"Number\", \"brunnel\": \"String\", \"service\": \"String\" } }, { \"id\": \"building\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"render_height\": \"Number\", \"render_min_height\": \"Number\" } }, { \"id\": \"water_name\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"name\": \"String\", \"name_en\": \"String\", \"class\": \"String\" } }, { \"id\": \"transportation_name\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"name\": \"String\", \"ref\": \"String\", \"ref_length\": \"Number\", \"class\": \"String\" } }, { \"id\": \"place\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"name\": \"String\", \"name_en\": \"String\", \"class\": \"String\", \"rank\": \"Number\", \"capital\": \"Number\" } }, { \"id\": \"housenumber\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"housenumber\": \"String\" } }, { \"id\": \"poi\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"name\": \"String\", \"name_en\": \"String\", \"class\": \"String\", \"subclass\": \"String\", \"rank\": \"Number\" } } ] }",
"maskLevel": "8",
"maxzoom": "14",

```

**Comment by ericfischer** [comment] 2017-04-12 19:34
OK, this is actually kind of interesting, because I think it's the wrapper FeatureCollections that are building up in memory. Tippecanoe cleans up each Feature after it finds the end of it, but it never cleans up FeatureCollections so they just accumulate until it reaches the end of the file.

It should be a pretty straightforward fix, so I'll follow up soon. Thanks for the report!

**Comment by nodefiend** [comment] 2017-04-12 19:37
WOw thanks eric!!

**Comment by nodefiend** [comment] 2017-04-12 19:38
i can get you a file with more lines ? how many lines would you want to see

**Comment by nodefiend** [comment] 2017-04-12 19:44
```
{ "type": "FeatureCollection", "properties": {
"attribution": "<a href=\"http://openmaptiles.org/\" target=\"_blank\">&copy; OpenMapTiles</a> <a href=\"http://www.openstreetmap.org/about/\" target=\"_blank\">&copy; OpenStreetMap contributors</a>",
"bounds": "-180,-85.0511,180,85.0511",
"center": "-12.2168,28.6135,4",
"description": "http://openmaptiles.org",
"format": "pbf",
"id": "openmaptiles",
"json": "{ \"vector_layers\": [ { \"id\": \"water\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\" } }, { \"id\": \"waterway\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"name\": $
"maskLevel": "8",
"maxzoom": "14",
"minzoom": "0",
"name": "OpenMapTiles",
"version": "3.3"
}, "features": [
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14015 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14014 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14013 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14012 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14011 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14010 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14009 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14008 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14007 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14006 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14005 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14004 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14003 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14002 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14001 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 14000 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13999 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13998 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13997 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13996 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13995 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13994 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13993 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13992 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13991 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13990 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13989 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13988 }, "features": [
] }
,
{ "type": "FeatureCollection", "properties": { "zoom": 14, "x": 0, "y": 13987 }, "features": [
] }

```

**Comment by ericfischer** [comment] 2017-04-12 19:46
This will be fixed in https://github.com/mapbox/tippecanoe/pull/395

**Comment by nodefiend** [comment] 2017-04-12 19:57
eric, just wondering should i update tippecanoe and then run ```tippecanoe-decode``` on the giant mbtiles file again, seperating out the layers as needed?

**Comment by ericfischer** [comment] 2017-04-12 20:03
You will need to upgrade Tippecanoe, but the `tippecanoe-decode` will not change. The change is within `tippecanoe` itself.

**Comment by nodefiend** [comment] 2017-04-12 20:06
okay great! thanks so much, i managed to increase the swap space on my EC 2 instance to 50gigs , the tippecanoe file is usually smaller than the geojson file , so it should be fine.

**Comment by ericfischer** [comment] 2017-04-12 20:08
I think it should need a lot less swap space after this change.

**Comment by nodefiend** [comment] 2017-04-12 20:09
woo hoo! glad i could be even a small part of help to the library! :D

**Comment by ericfischer** [comment] 2017-04-12 20:20
Merged! Please reopen if it still runs out of memory for you.

**Closed by ericfischer** 2017-04-12 20:20 UTC

**Comment by nodefiend** [comment] 2017-04-14 03:03
@ericfischer 

In your experience, do you know a rough estimate about how much space swap space will i need to run tippe canoe for zoom 1 on 2 geojson layer files

60g - z14_transportation.geojson
280g - z14_water.geojson 

i just want to run tippecanoe on 1 zoom layer using both of these files

I keep running out of memory on my ec2 instance when i try to run this conversion

it says disk is out of memory.

**Comment by ericfischer** [comment] 2017-04-14 05:03
If you are running out of disk space, make sure to use `-t` to make Tippecanoe put its temporary files on a drive that has lots of space, if your `/tmp` is on a different drive than you have lots of space on.

I would say it typically needs 25% to 50% of the size of the original GeoJSON for temporary files, but it can vary a lot based on how much duplication there is between feature attributes.

**Comment by nodefiend** [comment] 2017-04-14 22:31
okay great thanks going to start processing these files now with -t

**Comment by nodefiend** [comment] 2017-04-16 06:11
@ericfischer 

Using an unbuntu EC2 large instance

I used -t (on ``tippecanoe``) and pointed it to a volume that had over 500g of free space

I ran `sudo nohup` inside of screen  

I ran this command to create a mbtiles file for zoom 1 level:

```
sudo tippecanoe -o zoom1.mbtiles -t /data -z1 -Z1 -f -F -pS -pf -pk -pc -pt -Bg -X -an -as -pd -S9 -al -rg ./z14_transportation.geojson ./z14_water.geojson

```

I let it run , and checked the output of ``nohup`` and i got this:

<img width="633" alt="screen shot 2017-04-15 at 11 01 53 pm" src="https://cloud.githubusercontent.com/assets/10778319/25069253/b5710584-2230-11e7-9c70-051978849f86.png">

**Comment by nodefiend** [comment] 2017-04-16 06:14
Not sure what bad_alloc is referring to , but I do see it say try -gl to limit near duplicates , maybe that is a possible route to try?

**Comment by nodefiend** [comment] 2017-04-16 16:59
Alright, just turned on the server, runnng conversions with g1 , hopefully that will help with the duplicates

**Comment by ericfischer** [comment] 2017-04-16 17:59
The `std::bad_alloc` is the C++ memory allocator running out of memory.

From the screenshot, it looks like it has successfully made it through parsing the GeoJSON and reordering the features, so it must be failing during tiling. You have enough disk storage now, but still not enough RAM or swap.

The `-g1` warning is because you've used `-Bg` to guess a base zoom level, and even the high-zoom tiles have a lot of features in them. For what you are doing, I don't think the base zoom level is actually relevant so `-g1` isn't going to help. The "duplicates" it is trying to warn about are points that are very near each other, so it is not going to do anything to help with these polygons.

Anyway, it appears to be crashing during tiling by running out of memory, as it tries to read everything that it think should be in the top-level tile 0/0/0 into memory all at once. The problem is that `--drop-fraction-as-needed` should drop some fraction of these features, but it doesn't know to drop them until it tries to make the tile, which requires the full list of features to have already fit in memory, which can't happen because there isn't enough memory.

So I think the answer is that tiling probably needs a "this can't possibly work" short-circuit that detects overfull tiles and jumps ahead to doing fractional feature dropping before it even makes it through loading all the features for the tile into memory. The hard part is it doesn't know that it's about to run out of memory until it actually happens, but it should be possible to compare against an approximation to the real memory size.

In the meantime, you might want to try `-Z5` or something like that so that it never actually tries to make a zoom level 0 tile and instead starts out at some higher zoom level that is more likely to succeed.

**Comment by nodefiend** [comment] 2017-04-17 14:43
Thanks @ericfischer !

removed BG , and added a swapfile of 300gb

running conversions on zoom level 5! *crosses fingers*

```sudo nohup tippecanoe -o zoom5.mbtiles -t /data -z5 -Z5 -f -F -pS -pf -pk -pc -pt -X -an -as -pd -S9 -al -rg ./z14_transportation.geojson ./z14_water.geojson```

**Comment by ericfischer** [comment] 2017-04-17 16:06
Hope that works for you. By the way, the transportation layer is going to be *much* easier to tile than the water. The water is going to be bogged down by oceans full of identical square polygons of water, which massively bloat both the tileset and the memory usage.
