### ISSUE TITLE
Tippecanoe consistently freezes up with complex geometry

### ISSUE THREAD

**Issue by nsamala** [mapbox/tippecanoe#132] opened 2015-12-21 18:38 UTC
We have a large national parks GeoJSON dataset with large, complex geometry (the Appalachian trail for example). Tippecanoe consistently freezes up around ~23% whenever that dataset is included. I've tried to dive into the code to figure out where this is happening, but I'm not sure how to debug that.

Any ideas?

**Comment by morganherlocker** [comment] 2015-12-21 18:39
@nsamala Can you post a link to the failing data, so we can make a test case?

**Comment by ericfischer** [comment] 2015-12-21 18:40
@nsamala What version of tippecanoe are you using? There were some bad performance problems with polygons that were fixed in https://github.com/mapbox/tippecanoe/issues/121, so I hope that may help with your dataset too.

**Comment by nsamala** [comment] 2015-12-21 18:43
@ericfischer I'm using 1.4.1. I'll pull down changes to see if anything has changed. @morganherlocker Lemme check with the office peeps to see if it's cool to link to the data.

**Comment by ericfischer** [comment] 2015-12-21 19:22
https://github.com/kgjenkins/ophz/tree/master/shp is another good example of a giant, complex polygon that is very slow to tile.

**Comment by nsamala** [comment] 2015-12-21 19:35
Sorry for the delay on the file! You can check it out [here](http://1drv.ms/1UXVtcK).

I tried running line simplification on it which halved the file size. Tippecanoe was able to process up to 50% of the resultant file.

**Comment by ericfischer** [comment] 2015-12-21 19:47
Thanks @nsamala! I'll give it a try in a moment.

I wonder if the right thing to do is to do fast, simple clipping for the purposes of tiling, and to only bring Clipper's careful work into it as a final output stage in each tile after scaling and line simplification.

**Comment by ericfischer** [comment] 2015-12-21 19:52
The plant hardiness shapefile does eventually complete, after 46m34.026s of CPU time, but the low zooms are very slow.

**Comment by nsamala** [comment] 2015-12-21 20:22
@ericfischer I think that would be a good idea to use fast, simple clipping for tiling. 

I'll probably dive into the code for good today, so I apologize if this is already addressed: maybe you could write out temp files by tile level and then utilize child threads to process each individual tile in further detail and add it to the MBTile.

**Comment by ericfischer** [comment] 2015-12-21 21:11
@nsamala Versions since 3fbd0d654695a01ec61 do already use multiple threads while tiling, so unfortunately the problem can't be masked just by spreading it over more CPUs. (There may be a better way to do the scheduling, though, since it doesn't necessarily know which tiles will be the slow ones at the time that it partitions out the tasks.)

The low zooms feel faster with simple clipping, but apparently it actually hurt in practice: 55m54.858s of CPU.

So a new idea: maybe I can run everything through Clipper once at z0 to clean it up, using all the CPUs that would otherwise go to waste at that zoom, and then at the higher zooms do a cheap clip and then another final cleanup.

**Comment by ericfischer** [comment] 2015-12-21 21:31
Although there are big up-front costs to that idea. It has been cleaning polygons for at least 10 minutes and is still going. Still to be seen whether that will pay off in faster processing of the higher zooms.

**Comment by nsamala** [comment] 2015-12-21 21:45
Is it just because of the sheer number of points in the polygon that makes this difficult to process?

And another update: I ran an even more aggressive line simplification algorithm and I was able to get it to process the data, but obviously that's not a great solution for some use cases.

**Comment by ericfischer** [comment] 2015-12-21 22:01
@nsamala Yes, that's what it looks like. I'm not entirely sure how to characterize the performance, but essentially it looks like performance is predictably good up to about 700 sides on a polygon, and then blows up badly for polygons with tens of thousands of sides.

![screen shot 2015-12-21 at 1 58 07 pm](https://cloud.githubusercontent.com/assets/1951835/11942412/2a7a3434-a7eb-11e5-841c-5a3cf81cc09e.png)

So I should probably dynamically simplify each polygon down to some reasonable number of sides, independent of the tile resolution, to keep performance good.

**Comment by ericfischer** [comment] 2015-12-21 22:41
Geometric simplification of polygons doesn't seem to help much: it's still 45 minutes of CPU. So maybe the problem is topological complexity with lots of holes, instead?

**Comment by nsamala** [comment] 2015-12-21 22:48
That's possible. I used Mapshaper's weighted Visvalingam algorithm which is doing some sort of black magic. After that, Tippecanoe was able to rip through and present geometry that looked pretty close to the original.

**Comment by ericfischer** [comment] 2015-12-21 23:15
I'll have to try switching simplification algorithms and see if that helps.

For the record, the whole thing without using Clipper is 7m40.979s. There's got to be some way to guarantee clean polygon geometries without spending 6x the time.

**Comment by ericfischer** [comment] 2016-02-11 18:43
My new plan for this is just to cut up complex polygons into smaller features until each of them has few enough vertices to be tractable, rather than hoping to simplify the complexity away.

**Comment by ericfischer** [comment] 2016-02-11 20:18
Working on this in https://github.com/mapbox/tippecanoe/pull/170

**Comment by nsamala** [comment] 2016-02-11 21:12
Been messing around with the geojson-vt project over the past couple days. Would it work to adopt a divide-and-conquer strategy similar to that for generating tiles at higher zoom levels?

**Comment by ericfischer** [comment] 2016-02-11 22:02
What I am doing in https://github.com/mapbox/tippecanoe/pull/170 basically is dividing and conquering: cutting the polygon in half horizontally or vertically until it is simple enough. Is that what you had in mind?

**Comment by nsamala** [comment] 2016-02-11 22:16
Pretty much, it divides each tile and uses that tile's subset of the geometry to do tiling at the next level down.

You might even be able to leverage the [C++ port of geojson-vt](https://github.com/mapbox/geojson-vt-cpp). I'm not sure whether or not that's more or less effort.

**Comment by ericfischer** [comment] 2016-02-11 22:20
That is the same thing tippecanoe does in general for creating each successive zoom level. Lots of details are different because geojson-vt works entirely in memory while tippecanoe is optimized for data that is too large to consider all at once.

**Comment by ericfischer** [comment] 2016-02-11 22:21
(and geojson-vt is optimized for tiling only the data that you need to display what is on screen at any given moment, while tippecanoe is optimized for creating the entire tileset at once.)

**Comment by ericfischer** [comment] 2016-02-11 22:30
I just merged these changes and will be interested to know if your Appalachian Trail data now also tiles in a reasonable amount of time.

**Comment by nsamala** [comment] 2016-02-11 22:31
Ahh gotcha, yeah that makes sense. I know there are ways to force geojson-vt to render everything, but it does happen in memory. Thanks for the clarification.

**Comment by nsamala** [comment] 2016-02-11 22:31
Sweet, I'll give it a shot!

**Closed by ericfischer** 2016-02-11 22:30 UTC
