### ISSUE TITLE
Tippecanoe segfaults on Microsoft building footprint GeoJSON files

### ISSUE THREAD

**Issue by antifa-ev** [mapbox/tippecanoe#608] opened 2018-07-14 07:04 UTC
I've tried to convert GeoJSON files from the recent [Microsoft building footprint](https://github.com/Microsoft/USBuildingFootprints) data into MBTiles.

According to Nikola Trifunović the GeoJSON don't contain invalid entries anymore, but the conversion with tippecanoe leads to a crash at 49.9 %. All files I've tried until now crash when exceeding 49.9 %.

Maine ([Link](https://usbuildingdata.blob.core.windows.net/usbuildings-v1-1/Maine.zip)) / `tippecanoe -o Maine.mbtiles -zg --drop-densest-as-needed Maine.geojson`

**Comment by geeknik** [comment] 2018-07-16 02:12
I have been unsuccessful in reproducing a segfault with the latest `d64ac19` commit on Ubuntu 17.04 and the above linked data:

```
./tippecanoe -o /dev/shm/maine.mbtiles -zg --drop-densest-as-needed Maine.geojson
For layer 0, using name "Maine"
752054 features, 38871324 bytes of geometry, 752005 bytes of separate metadata, 0 bytes of string pool
Choosing a maxzoom of -z10 for features about 336 feet (103 meters) apart
Choosing a maxzoom of -z12 for resolution of about 70 feet (21 meters) within features
  99.9%  12/1264/1492
```

```
file /dev/shm/maine.mbtiles
/dev/shm/maine.mbtiles: SQLite 3.x database, last written using SQLite version 3019003
```
```
ll /dev/shm/maine.mbtiles
-rw-r--r-- 1 root root 20201472 Jul 16 02:07 /dev/shm/maine.mbtiles
```

```
md5sum /dev/shm/maine.mbtiles
60ec884d66677b94749d7861dd1f7dc2  /dev/shm/maine.mbtiles
```

**Comment by ericfischer** [comment] 2018-07-16 17:15
It works for me too, but if you can provide more information about the environment that it fails in, I can try to debug.

**Comment by ericfischer** [comment] 2018-07-24 15:30
Closing in the absence of information about how to reproduce

**Closed by ericfischer** 2018-07-24 15:30 UTC
