### ISSUE TITLE
metadata.json: No such file or directory while creating the tiles

### ISSUE THREAD

**Issue by Amit-Gore** [mapbox/tippecanoe#644] opened 2018-09-24 12:25 UTC
Hi, 
Whenever the geojson data changes, I have created this routine where I trigger running the set of Tippecanoe commands with mentioned layer and folder . 
I used to create a new directory(e.g. map_tiles_new, where already existing map_tiles folder will have the outdated tiles) and there I used to run the commands for fresh tiles. At the end I used to  replace the map_tiles_new folder with map_tiles folder

example command : 
`tippecanoe  --minimum-zoom=5 --maximum-zoom=6 --full-detail=18 --no-tile-compression --no-tile-size-limit --detect-longitude-wraparound --no-tiny-polygon-reduction  --progress-interval=3  --output-to-directory 'layer1' -l 'layer1' /home/ubuntu/data/*.geojson`

But now a days I am having this weird issue where if I run this command it will get completed to 100% but at the end it gives this error 'layer1/metadata.json: No such file or directory'. The map_tiles_new will have nothing there but the inode stat(IUsed) increases after the completion.

Any help ? And why do we need this metadata.json file ?

**Comment by ericfischer** [comment] 2018-09-24 17:17
The `metadata.json` file contains general information about the tileset: its name, the maxzoom and minzoom, the names of the layers, etc. If your application doesn't need it, then that's fine, but the Mapbox uploader insists upon it being there. It's the same information that documented here in the mbtiles spec: https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#vector-tileset-metadata

It looks like the problem with creating the `metadata.json` file is that Tippecanoe doesn't actually create the directory you specified with `--output-to-directory` until it tries to create the first tile, so if your data does not actually contain any valid geometries, the directory is never created and creating the `metadata.json` file within it fails.

I'll fix that. Thanks for the report.

**Comment by ericfischer** [comment] 2018-09-24 18:17
This will be fixed in https://github.com/mapbox/tippecanoe/pull/645

**Closed** 2018-09-24 20:52 UTC

**Comment by Amit-Gore** [comment] 2018-09-25 04:59
@ericfischer Thanks for the quick fix. So the source of this error is because of invalid feature geometries in geojson files? Surprisingly if I use --force option while running the command it works fine without throwing above error and the tiles are as expected.

**Comment by ericfischer** [comment] 2018-09-25 17:29
That was the way that I found to reproduce it: an input file that *has* features (so it doesn't stop early with a complaint that there are no features) but with them all off the edge of the earth so no tiles are actually generated.

Maybe there is some other way to trigger it. If you found another way, let me know.

That is weird that `--force` would make a difference, since if anything that should be *removing* the `metadata.json`, not creating it. Maybe it is removing an old one that has the wrong permissions or something?
