### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by chrislukic** [mapbox/tippecanoe#81] opened 2015-09-15 16:19 UTC
Any thoughts on creating package for Windows? Or perhaps adding instructions for creating a windows build to the documentation?

**Comment by ericfischer** [comment] 2015-09-15 17:49
I hope I can make it work on Windows, but I don't think it's going to be easy, since it relies heavily on memory-mapped files. Maybe there's a compatibility layer somewhere that will provide an `mmap`-like interface in Windows.

**Comment by chrislukic** [comment] 2015-09-15 18:39
That was my worry. I'm trying to implement a tippecanoe/Mapbox API upload workflow on a windows server. It would make things much easier to keep it all in the same environment.

Admittedly out of my depth, but some Google research seems to suggest [MapViewOfFile](https://msdn.microsoft.com/en-us/library/aa366761.aspx) might be of use.

**Comment by BergWerkGIS** [comment] 2015-09-19 17:39
There seems to be a Windows port of `mmap` (https://code.google.com/p/mman-win32/source/browse/#svn%2Ftrunk), but it looks abandoned (files are 3 years old).

I took a quick stab and tried to get tippecanoe compile on Windows.
https://github.com/mapbox/tippecanoe/compare/master...BergWerkGIS:master?diff=split&name=master

I was **not** successfull and don't have the bandwidth to pursue, as there are also some other code changes necessary.

e.g. variable length arrays are not supported by Visual Studio:

```c
char *metakey[nprop];
char *metaval[nprop];
int metatype[nprop];
```
https://github.com/mapbox/tippecanoe/blob/18647d18dd30a0b171ed429dd043b25855b4a517/geojson.c#L454-L456

**Comment by ericfischer** [comment] 2015-09-22 17:09
Thanks for trying to make it work!

I could probably work around the variable-length arrays just by dragging more of the code onto the C++ side and using vectors instead of arrays, and will prioritize that if it will help you.

**Comment by BergWerkGIS** [comment] 2015-09-23 11:47
@ericfischer 

> dragging more of the code onto the C++ side and using vectors instead of arrays, and will prioritize that if it will help you.

Cool, would be really great to have tippecanoe on Windows, too.
Could you ping me after you have refactored, that I can give it another try.

**Comment by chrislukic** [comment] 2015-10-02 13:29
Any further thoughts on this? I'm approaching a crossroads soon, and debating whether to start looking into adding a linux server for the Tippecanoe workflow. I'd definitely like to avoid this, but don't want to pin my hopes on a low probability outcome.

**Comment by rowanwins** [comment] 2015-12-16 22:05
Gday all,

Just throwing in a quick comment here although I know next to nothing about memory mapped files or C++...

It looks like the [boost library](http://www.boost.org/) provides a cross-platform solution to [memory mapped files].(http://www.boost.org/doc/libs/1_50_0/libs/iostreams/doc/classes/mapped_file.html#mapped_file). 

Someone has thrown together some sample code [here](http://codingplayground.blogspot.com.au/2009/03/memory-mapped-files-in-boost-and-c.html) which might show a bit of a starting point. 

Wish I could help more because I'd love to see tippecanoe working on windows machines :)

Cheers
Rowan

**Comment by ericfischer** [comment] 2015-12-17 18:47
Sorry to have missed your message on Oct 2, @chrislukic!

I'll have to try the boost abstraction, @rowanwins. Thanks for telling me about it! I hope I'll have a chance to try this, but I have absolutely no Windows development experience so I hope no one is counting on having this be available any time soon.

**Comment by rowanwins** [comment] 2015-12-18 00:19
no rush here @ericfischer , give me a yell if you need someone to do some testing/attempted debugging!

**Comment by ericfischer** [comment] 2016-03-30 18:25
Sounds like Linux command line tools [may soon work unchanged on Windows](http://blog.dustinkirkland.com/2016/03/ubuntu-on-windows.html).

**Comment by chrislukic** [comment] 2016-03-30 18:39
Such a strange and wonderful thing.

**Comment by jingsam** [comment] 2016-04-01 01:20
Use Cygwin. Tippecanoe works unmodified on Cygwin.

**Comment by ericfischer** [comment] 2016-04-01 17:21
Oh fantastic, that's great to hear @jingsam!

**Comment by BergWerkGIS** [comment] 2016-05-20 09:09
Thanks, @jingsam for verifying that Cygwin is a workaround.
Closing for now, maybe revisit when `Bash on Windows` is generally available.

**Closed by BergWerkGIS** 2016-05-20 09:09 UTC

**Comment by chrislukic** [comment] 2016-05-23 02:07
@jingsam First time Cygwin user, so any help is much appreciated. Installed devel zlib, sqllite, make, g++, packages, but still get this error from the make. 

![image](https://cloud.githubusercontent.com/assets/3892399/15458508/736e2000-209b-11e6-9f57-871e1c62d13e.png)

**Comment by chrislukic** [comment] 2016-05-23 02:31
@jingsam Was eventually able to get it to build. Added the flag -U__STRICT_ANSI__ to the make file. thx.

**Comment by ericfischer** [comment] 2016-05-23 16:44
Thanks @chrislukic. I'm glad you were able to get it working!

**Comment by BergWerkGIS** [comment] 2016-05-27 10:13
> Sounds like Linux command line tools [may soon work unchanged on Windows](http://blog.dustinkirkland.com/2016/03/ubuntu-on-windows.html).

YES!
Just updated to the latest Windows Insider Preview Build of Windows 10 and installed [Ubuntu Bash on Windows](
https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/).

Built a `tippecanoe` release build (with `clang@3.5`) without any modifications and `make test` finished without any errors.

-----

Remember: the resulting binaries are native ELF binaries and not Windows binaries.

```
bergw@MB:~/tippecanoe$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
bergw@MB:~/tippecanoe$
```

**Comment by ericfischer** [comment] 2016-05-27 19:00
Thanks for checking on this, @BergWerkGIS! Glad to hear it works.

**Comment by sainsb** [comment] 2016-11-16 02:38
For those ultimate cpp noobs - append the `-U__STRICT_ANSI__` to line 10 CXXFLAGS of the makefile.

Was able to build in Cygwin on windows after applying @chrislukic solution

**Comment by lihuadong1988** [comment] 2017-03-08 10:36
@chrislukic tippecanoe works very slow if json file is too big,have you ever met this question?

**Comment by chrislukic** [comment] 2017-03-08 11:20
@lihuadong1988 Unfortunately yes. Performance was a big enough issue, we ended up abandoning cygwin and moving the processing to AWS.

**Comment by pathmapper** [comment] 2018-01-23 13:11
Just found this step-by-step guide for Tippecanoe with Cygwin and tried it successfully on Windows 7:
https://github.com/GISupportICRC/ArcGIS2Mapbox#installing-tippecanoe-on-windows

**Comment by ericfischer** [comment] 2018-01-23 18:19
Thank you @pathmapper! I'll add that link to the documentation.

**Comment by jingsam** [comment] 2018-01-24 08:29
I have made two days efforts trying to make tippecanoe work on Windows. There are 4 ways:

1. Use `Ubuntu Bash on Windows`.  Tippecanoe works perfectly on WSL. I did not test the performance on this environment. The problem is that `Ubuntu Bash on Windows` is only available on Windows 10 or the latest Windows Server. So the way is not working on Windows 7 or XP.

2. Use `Cygwin`. `Cygwin` provides a POSIX environment on Windows. Tippecanoe can be compile with `-U__STRICT_ANSI__` flag in Cygwin. This way works on any version of Windows. The problem is that the performance is very low when you have to process large geojson files.

3. Use `VirtualBox`. You can install a linux environment in VirtualBox. The way also works on any versions of Windows. The problem is that it seems too heavy to install tippecanoe on Windows. The performance is not tested. I guess it will be even lower than `Cygwin`.

4. Use `MinGW-w64`.  I am trying to compile a native tippecanoe with `MinGW` and not yet succeed. Tippecanoe is POSIX compatible, not cross-platform. It heavily relys on some POSIX headers as  follows:
```
#include <sys/time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/sysctl.h>
#include <sys/mman.h>
#include <sys/resource.h>
#include <sys/param.h>
#include <sys/mount.h>
#include <sys/statfs.h>
#include <sys/wait.h>
```
`MinGW` provides some POSIX headers, but most of them is not available. For now I think it is not possible to make a native tippecanoe on windows using `MinGW`.

Option 4 is the only possible way to make tippecanoe works efficiently on any versions of Windows. However, Option 4 is not possible for now. 

The fact that Tippecanoe can not works natively on Windows is indeed a pain for me. My use case is that our data processing environment are all Windows 7 and offline. The data we need to process is very large, from hundreds of GBs to TBs. So we urge to find high performance vector tiles generating tools.

So, Could you give us some suggestions or tips to make tippecanoe work natively on Windows. Are these POSIX features vital to tippecanoe? Can we find alternatives  of these features on Windows? We want to help to make it work. If you provide some tips, maybe the processing would be a little easier.

**Comment by ericfischer** [comment] 2018-01-24 18:12
Thanks for digging into this @jingsam.

Yes, Tippecanoe depends heavily on memory-mapped I/O (`<sys/mman.h>`), so it is not possible to implement strictly within Standard C without any operating system extensions. That said, Windows *does* have APIs for memory-mapped I/O. I just don't know anything about them myself.

The one extra-Unixy thing that Tippecanoe does is to open temporary files and then immediately delete them so that they are anonymous. I don't think that works on Windows, but Tippecanoe could be changed to delete its temporary files after it is done with them instead.

Going through these headers in order:

* `sys/time.h` is probably actually not necessary
* `sys/types.h` is needed for creating POSIX threads
* `sys/stat.h` is needed to find the sizes of files. Could be replaced by a Windows API
* `sys/sysctl.h` is needed to find the size of main memory on MacOS. Could be replaced by a Windows API.
* `sys/mman.h` is needed to memory-map files. Could be replaced by a Windows API
* `sys/resource.h` is needed to check how many files can be open at once. Could be replaced by a Windows API.
* `sys/param.h` is MacOS-only and may not actually be needed
* `sys/mount.h` is needed to check how much disk space is available on MacOS. Could be replaced by a Windows API or stubbed out.
* `sys/statfs.h`  is needed to check how much disk space is available on Linux. Could be replaced by a Windows API or stubbed out.
* `sys/wait.h` is needed to start child processes for shell filters. This mechanism would probably need to be removed on Windows.

**Comment by medv** [comment] 2018-04-13 05:13
https://hub.docker.com/r/jskeates/tippecanoe/

**Comment by skaletech** [comment] 2018-05-02 14:04
So, there are some libraries already ported to windows:

[mman-win32](https://github.com/witwall/mman-win32)
zlib is on nuget
pthreads is on nuget

Alot of the rest could be resolved with libgwin32c, but I am not a c/c++ expert anymore.

It would be really slick to be able to run this on windows.

**Comment by ericfischer** [comment] 2018-05-04 17:29
@bblacksh I think I probably need to add

```
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
```

to the top of `write_json.cpp` so Cygwin will get the declaration of `vasprintf`. If this works for you, please let me know and I'll add it.

**Comment by bblacksh** [comment] 2018-05-04 17:34
yep, that did it, thanks!

**Comment by jmasselink** [comment] 2018-05-15 00:40
I'm experiencing the error with vasprintf when compiling with CygWin but in the tile-join.cpp file. 
Added the def to the top of tile-join.cpp and this error disappeared.
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

**Comment by ericfischer** [comment] 2018-05-15 00:42
Thanks @jmasselink. Tile-join also uses `vasprintf` so I'll add the `#define` there.

**Comment by ericfischer** [comment] 2018-05-15 00:44
This will be in https://github.com/mapbox/tippecanoe/pull/569
